title: Yuva Conclave 2024
email: saurabhnage624@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Official website for Yuva Conclave 2024.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.thebrewery.co.in/event-details/yi-youth-conclave-laughter-to-leadership" # the base hostname & protocol for your site
twitter_username: YiVadodara
github_username: Saurabhnage
